on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created

jobs:
  bot:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        repository: myopenfactory/actions
        ref: refs/heads/main
        token: ${{ secrets.MYOFBOT_PAT }}
    - name: myofbot
      uses: ./myofbot
      with:
        token: ${{ secrets.MYOFBOT_PAT }}
